FROM apache/airflow:2.10.2-python3.11

USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

USER airflow
WORKDIR /opt/airflow

COPY pyproject.toml /opt/airflow/pyproject.toml
COPY src /opt/airflow/src

RUN pip install --no-cache-dir -e /opt/airflow
